export const CartActionsType = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_ACTION",
  ADD_TO_CART: "ADD_TO_CART",
  DECREASE_ITEMS: "DECREASE_ITEMS",
  ENLARGE_ITEMS: "ENLARGE_ITEMS",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
